### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by milibopp** [mitsuhiko/unp#15]
@mitsuhiko is this tool still maintained?

It is a great usability benefit for command-line users, so it would be sad to see it die slowly. I am mainly wondering, as I was thinking about packaging it for NixOS.

**Comment by mitsuhiko** [comment]
I fix it for my own issues only atm.

**Comment by Moredread** [comment]
There are alternatives like unp from Debian, dtrx, atool, unar, and I think I saw one written in go, but can't find it.

**Comment by milibopp** [comment]
@Moredread, thanks for the hint.

**Comment by chocolateboy** [comment]
As well as [aunpack](https://linux.die.net/man/1/aunpack) (part of the aforementioned [atool](https://www.nongnu.org/atool/)) there's also a new version of this tool by the same author written in Rust: [unbox](https://github.com/mitsuhiko/unbox).
